# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.0.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(927, 610)
        self.actionNew_Substrate = QAction(MainWindow)
        self.actionNew_Substrate.setObjectName(u"actionNew_Substrate")
        self.actionLoad = QAction(MainWindow)
        self.actionLoad.setObjectName(u"actionLoad")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionSave.setCheckable(False)
        self.actionExport_to_XML = QAction(MainWindow)
        self.actionExport_to_XML.setObjectName(u"actionExport_to_XML")
        self.actionLink = QAction(MainWindow)
        self.actionLink.setObjectName(u"actionLink")
        self.actionCell_Definitions = QAction(MainWindow)
        self.actionCell_Definitions.setObjectName(u"actionCell_Definitions")
        self.actionXML_Out = QAction(MainWindow)
        self.actionXML_Out.setObjectName(u"actionXML_Out")
        self.action2D = QAction(MainWindow)
        self.action2D.setObjectName(u"action2D")
        self.action3D = QAction(MainWindow)
        self.action3D.setObjectName(u"action3D")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.Outline = QTreeWidget(self.centralwidget)
        __qtreewidgetitem = QTreeWidgetItem()
        __qtreewidgetitem.setTextAlignment(0, Qt.AlignLeading|Qt.AlignVCenter);
        self.Outline.setHeaderItem(__qtreewidgetitem)
        QTreeWidgetItem(self.Outline)
        QTreeWidgetItem(self.Outline)
        self.Outline.setObjectName(u"Outline")
        self.Outline.setGeometry(QRect(0, 0, 181, 561))
        self.Outline.setColumnCount(1)
        self.New = QPushButton(self.centralwidget)
        self.New.setObjectName(u"New")
        self.New.setGeometry(QRect(290, 40, 91, 23))
        self.Remove = QPushButton(self.centralwidget)
        self.Remove.setObjectName(u"Remove")
        self.Remove.setGeometry(QRect(650, 40, 111, 23))
        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(290, 70, 451, 471))
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 449, 469))
        self.label_5 = QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(60, 230, 101, 21))
        self.label_4 = QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(60, 180, 101, 21))
        self.label_3 = QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(60, 130, 101, 21))
        self.label_2 = QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(60, 80, 101, 21))
        self.label = QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(60, 30, 101, 21))
        self.name = QLineEdit(self.scrollAreaWidgetContents)
        self.name.setObjectName(u"name")
        self.name.setGeometry(QRect(170, 30, 161, 20))
        self.checkBox = QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(30, 230, 16, 16))
        self.checkBox.setChecked(False)
        self.diffusionCoeff = QLineEdit(self.scrollAreaWidgetContents)
        self.diffusionCoeff.setObjectName(u"diffusionCoeff")
        self.diffusionCoeff.setGeometry(QRect(170, 80, 161, 20))
        self.diffusionCoeff.setInputMethodHints(Qt.ImhDigitsOnly)
        self.decayRate = QLineEdit(self.scrollAreaWidgetContents)
        self.decayRate.setObjectName(u"decayRate")
        self.decayRate.setGeometry(QRect(170, 130, 161, 20))
        self.initialCond = QLineEdit(self.scrollAreaWidgetContents)
        self.initialCond.setObjectName(u"initialCond")
        self.initialCond.setGeometry(QRect(170, 180, 161, 20))
        self.dirchBoundary = QLineEdit(self.scrollAreaWidgetContents)
        self.dirchBoundary.setObjectName(u"dirchBoundary")
        self.dirchBoundary.setEnabled(True)
        self.dirchBoundary.setGeometry(QRect(170, 230, 161, 20))
        self.label_6 = QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(130, 270, 111, 16))
        self.label_7 = QLabel(self.scrollAreaWidgetContents)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(130, 310, 71, 21))
        self.label_8 = QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(130, 350, 71, 21))
        self.label_9 = QLabel(self.scrollAreaWidgetContents)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(130, 390, 71, 21))
        self.label_10 = QLabel(self.scrollAreaWidgetContents)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(130, 430, 71, 21))
        self.lineEdit_6 = QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(210, 310, 161, 20))
        self.lineEdit_7 = QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(210, 350, 161, 20))
        self.lineEdit_8 = QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setGeometry(QRect(210, 390, 161, 20))
        self.lineEdit_9 = QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setGeometry(QRect(210, 430, 161, 20))
        self.checkBox_2 = QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(100, 310, 16, 16))
        self.checkBox_3 = QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_3.setObjectName(u"checkBox_3")
        self.checkBox_3.setGeometry(QRect(100, 350, 16, 16))
        self.checkBox_4 = QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_4.setObjectName(u"checkBox_4")
        self.checkBox_4.setGeometry(QRect(100, 390, 16, 16))
        self.checkBox_5 = QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_5.setObjectName(u"checkBox_5")
        self.checkBox_5.setGeometry(QRect(100, 430, 16, 16))
        self.label_11 = QLabel(self.scrollAreaWidgetContents)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(340, 80, 71, 16))
        self.label_12 = QLabel(self.scrollAreaWidgetContents)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(340, 130, 47, 13))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.Clone = QPushButton(self.centralwidget)
        self.Clone.setObjectName(u"Clone")
        self.Clone.setGeometry(QRect(390, 40, 91, 23))
        MainWindow.setCentralWidget(self.centralwidget)
        self.scrollArea.raise_()
        self.Outline.raise_()
        self.New.raise_()
        self.Remove.raise_()
        self.Clone.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 927, 21))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuNew = QMenu(self.menuFile)
        self.menuNew.setObjectName(u"menuNew")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menuFile.addAction(self.menuNew.menuAction())
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuNew.addAction(self.action2D)
        self.menuNew.addAction(self.action3D)
        self.menuView.addAction(self.actionXML_Out)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionNew_Substrate.setText(QCoreApplication.translate("MainWindow", u"New Substrate", None))
        self.actionLoad.setText(QCoreApplication.translate("MainWindow", u"Load", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.actionExport_to_XML.setText(QCoreApplication.translate("MainWindow", u"Export to XML", None))
        self.actionLink.setText(QCoreApplication.translate("MainWindow", u"Microenvironments", None))
        self.actionCell_Definitions.setText(QCoreApplication.translate("MainWindow", u"Cell Definitions", None))
        self.actionXML_Out.setText(QCoreApplication.translate("MainWindow", u"XML Out", None))
        self.action2D.setText(QCoreApplication.translate("MainWindow", u"2D", None))
        self.action3D.setText(QCoreApplication.translate("MainWindow", u"3D", None))
        ___qtreewidgetitem = self.Outline.headerItem()
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("MainWindow", u"New 2D", None));

        __sortingEnabled = self.Outline.isSortingEnabled()
        self.Outline.setSortingEnabled(False)
        ___qtreewidgetitem1 = self.Outline.topLevelItem(0)
        ___qtreewidgetitem1.setText(0, QCoreApplication.translate("MainWindow", u"Microenvironment", None));
        ___qtreewidgetitem2 = self.Outline.topLevelItem(1)
        ___qtreewidgetitem2.setText(0, QCoreApplication.translate("MainWindow", u"Cell Definitions", None));
        self.Outline.setSortingEnabled(__sortingEnabled)

        self.New.setText(QCoreApplication.translate("MainWindow", u"New Substrate", None))
        self.Remove.setText(QCoreApplication.translate("MainWindow", u"Remove Substrate", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Dirichlet Boundary", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Initial Condition", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Decay Rate", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Diffusion Coefficient", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Name", None))
        self.name.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Default", None))
        self.checkBox.setText("")
        self.diffusionCoeff.setPlaceholderText(QCoreApplication.translate("MainWindow", u"0", None))
        self.decayRate.setPlaceholderText(QCoreApplication.translate("MainWindow", u"0", None))
        self.initialCond.setPlaceholderText(QCoreApplication.translate("MainWindow", u"0", None))
        self.dirchBoundary.setPlaceholderText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Advanced Boundary", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"X Maximum", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"X Minimum", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Y Maximum", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Y Minimum", None))
        self.lineEdit_6.setPlaceholderText(QCoreApplication.translate("MainWindow", u"0", None))
        self.lineEdit_7.setPlaceholderText(QCoreApplication.translate("MainWindow", u"0", None))
        self.lineEdit_8.setPlaceholderText(QCoreApplication.translate("MainWindow", u"0", None))
        self.lineEdit_9.setPlaceholderText(QCoreApplication.translate("MainWindow", u"0", None))
        self.checkBox_2.setText("")
        self.checkBox_3.setText("")
        self.checkBox_4.setText("")
        self.checkBox_5.setText("")
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"micron^2/min", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"1/min", None))
        self.Clone.setText(QCoreApplication.translate("MainWindow", u"Clone Substrate", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuNew.setTitle(QCoreApplication.translate("MainWindow", u"New", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
    # retranslateUi

